version: '3'

services:
  db:
    container_name: mysql8
    image: mysql:8
    restart: always
    volumes:
        - "./db/conf.d:/etc/mysql/conf.d"
        - "./db/data:/var/lib/mysql"
        - "./db/initdb.d:/docker-entrypoint-initdb.d"
        - "./data:/data"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'spring-batch-blog-db'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: Asia/Seoul
